import * as Styled from '~/styles/privacy-policy/styles.js';

const SectionNine = () => {
  const paragraphDivider = (
    <>
      <br />
      <br />
    </>
  );

  return (
    <>
      <Styled.Heading component="li">DISCLAIMERS AND LIMITATIONS OF LIABILITY</Styled.Heading>
      <Styled.Text>
        The express responsibilities set forth herein are the only responsibilities of the Company
        to you, and we have no other responsibilities to you with respect to the Platform. You
        acknowledge that the Company has no duty to take any action regarding: (a) which users gain
        access to the Platform (except authorized Commercial Users); (b) what Content you access or
        view via the Platform; (c) what effects Content you view on or through the Platform may have
        on you; (d) how you may interpret or use the Content; or (e) what actions you may take as a
        result of having been exposed to the Content.
        <ol>
          <Styled.SubHeading component="li">Warranty Disclaimers</Styled.SubHeading>
          <Styled.Text>
            YOUR USE OF THE PLATFORM, GENERALLY, IS ENTIRELY AT YOUR OWN RISK. THE PLATFORM AND ALL
            SOFTWARE, INFORMATION, CONTENT, PRODUCTS AND SERVICES WE PROVIDE THROUGH IT (1) ARE
            PROVIDED TO YOU ON “AS IS,” “WITH ALL FAULTS,” AND “AS AVAILABLE” BASES, (2) MAY INCLUDE
            ERRORS AND INACCURACIES REGARDING, AMONG OTHER THINGS, THE AVAILABILITY AND NATURE OF
            GOODS OR SERVICES OF COMMERCIAL USERS , AND (3) ARE OFFERED TO YOU WITHOUT ANY EXPRESS
            OR IMPLIED WARRANTIES OF ANY KIND, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AVAILABILITY, SATISFACTORY
            QUALITY, ACCURACY, COMPLETENESS, TIMELINESS, RELIABILITY, REASONABLE CARE, SECURITY,
            QUIET ENJOYMENT, NON-INFRINGEMENT OF INTELLECTUAL PROPERTY, OPERABILITY, FUNCTIONALITY,
            AND COMPLETENESS. MOREOVER, WE DO NOT REPRESENT, WARRANT, OR GUARANTEE THAT THE PLATFORM
            WILL: (A) BE UNINTERRUPTED, UNCOMPROMISED, OR FREE FROM PROBLEMS OR ANY TECHNICAL,
            TYPOGRAPHICAL, OR PHOTOGRAPHIC ERRORS; (B) BE FREE OF HACKING, INTERFERENCE, STATIC,
            VIRUSES, TROJAN HORSES, WORMS, MALWARE, OR OTHER HARMFUL COMPONENTS; (C) BE SECURE AND
            AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (D) BE CURED OR CORRECTED OF ALL ERRORS
            AND DEFECTS EVEN IF THE COMPANY IS AWARE OF THEM; AND (E) MEET ALL OF YOUR REQUIREMENTS
            OR EXPECTATIONS. YOU ASSUME THE ENTIRE RISK OF ANY RELIANCE ON THE PLATFORM OR ITS
            CONTENTS.
          </Styled.Text>
          <Styled.SubHeading component="li">Company’s Liability Will Be Limited</Styled.SubHeading>
          <Styled.Text>
            YOU AGREE, TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, NOT TO HOLD THE COMPANY
            OR OUR SHAREHOLDERS, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, REPRESENTATIVES, SUPPLIERS,
            PARTNERS, AFFILIATES, OR LICENSEES RESPONSIBLE OR LIABLE FOR ANY DAMAGES OR REMEDIES OF
            ANY KIND ARISING FROM YOUR USE OF THIS WEBSITE OR THE SERVICE, OR FROM A DELAY OR
            INABILITY TO ACCESS OR USE THIS WEBSITE (INCLUDING, BUT NOT LIMITED TO, YOUR RELIANCE
            UPON THIRD PARTY INFORMATION, CONTENT, USER CONTENT, REVIEWS AND OPINIONS APPEARING ON
            THE SERVICE, VIRUSES, ERRORS, LINKED SITES, PROPERTIES, PRODUCTS, AND SERVICES OBTAINED
            THROUGH THE SERVICE) INCLUDING BUT NOT LIMITED TO ANY INDIRECT, INCIDENTAL, SPECIAL,
            EXEMPLARY, PUNITIVE, LOST PROFITS, LOST GOODWILL, LOST DATA, WASTE OF EXPENDITURES, COST
            OF SUBSTITUTE, AND CONSEQUENTIAL DAMAGES, EVEN IF WE WERE EXPRESSLY ADVISED ABOUT THE
            POSSIBILITY OF SUCH DAMAGES. THIS LIMITATION APPLIES WHETHER THE DAMAGES ARE BASED IN
            CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE.
            {paragraphDivider}
            YOUR SOLE REMEDY FOR DISSATISFACTION WITH THE SITE IS TO STOP USING THE SITE. TO THE
            EXTENT COMPANY OR ANY OF OUR OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, REPRESENTATIVES,
            SUPPLIERS, PARTNERS, AFFILIATES, OR LICENSEES ARE FOUND LIABLE UNDER THE GOVERNING LAW
            FOR ANY LOSS OR DAMAGES OF ANY KIND ARISING FROM YOUR USE OF THE PLATFORM, OR THE
            CONTENT, SUCH LIABILITY IS EXPRESSLY EXCLUDED TO THE FULLEST EXTENT PERMITTED BY LAW;
            EXCEPT THAT THE TOTAL OF ANY SUCH LIABILITY SHALL BE LIMITED AND CAPPED IN AGGREGATE TO
            THE GREATER OF (A) REIMBURSEMENT OF THE TOTAL FEES PAID TO THE COMPANY BY YOU (IF ANY),
            (B) A MAXIMUM OF ONE THOUSAND U.S. DOLLARS ($1,000); OR THE MAXIMUM AMOUNT IN LIQUIDATED
            DAMAGES PERMITTED UNDER THE GOVERNING LAW. IN CASES WHERE APPLICABLE LAW DOES NOT ALLOW
            THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES, THE
            COMPANY’S LIABILITY WILL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.
            ALSO, CERTAIN LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR
            LIMITATION OF CERTAIN LIABILITIES OR DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF
            THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT
            HAVE ADDITIONAL RIGHTS. CONTENTS.
          </Styled.Text>
        </ol>
      </Styled.Text>
    </>
  );
};

export default SectionNine;
