const sixtyUntilNinetyNineArray = Array.from(Array(100).keys()).slice(-40);

const oneUntilNinetyNineArray = Array.from(Array(100).keys()).slice(-99);

export const ATTRIBUTES_ORDER = [
  'team',
  'number',
  'role',
  'jersey',
  'body',
  'hair',
  'accessories',
  'dunks',
  'shooting',
  'playmaking',
  'defense'
];

export const BALLERZ_PROPERTIES = {
  team: [
    'Alabama Kingpins',
    'Alaska Whales',
    'All-Stars',
    'Austin Machines',
    'Boston Rulers',
    'Boulder Elks',
    'Charlotte Clovers',
    'Chicago Squid',
    'Cleveland Firebirds',
    'D.C. Dobermans',
    'Dallas Pythons',
    'Delaware Horsemen',
    'Helena Pronghorns',
    'Houston Rogues',
    'Iowa City Rattlesnakes',
    'Las Vegas Scorpions',
    'Los Angeles Knives',
    'Los Angeles Mammoths',
    'Miami Tentacles',
    'Michigan Colliders',
    'Minneapolis Express',
    'Nashville Miracle',
    'New Jersey Scientists',
    'New Orleans Giants',
    'New York Golden Bulls',
    'New York Torches',
    'Omaha Bullsnakes',
    'Orlando Freeze',
    'Pennsylvania Fangs',
    'Phoenix Skulls',
    'Portland Bats',
    'Portland Creatures',
    'Salt Lake City Souls',
    'San Diego Keepers',
    'San Francisco Surge',
    'San Jose Sirens',
    'Seattle Scream',
    'Sierra Spiders',
    'St. Louis Orcs',
    'Tallahassee Tarantulas',
    'Tampa Bay Omens',
    'Team Dapper (M)',
    'Team Dapper (W)',
    'Team Flow (M)',
    'Team Flow (W)',
    'Toronto Spears',
    'Wisconsin Dragons'
  ],
  number: ['0', '00', ...oneUntilNinetyNineArray],
  role: ['All-Star', 'Captain', 'Player'],
  jersey: ['Away', 'Home'],
  body: [
    'Alien',
    'Bright Pink Alien',
    'Bright Zombie',
    'Devil',
    'Emoji',
    'Human',
    'Human I',
    'Human II',
    'Human III',
    'Human IV',
    'Human V',
    'Lizard',
    'Pink Alien',
    'Stone',
    'Zombie'
  ],
  hair: [
    'Afro',
    'Bedhead',
    'Black Long Ponytail',
    'Black Moptop',
    'Black Pigtails',
    'Black Pompadour',
    'Black Short',
    'Black Taper',
    'Blonde Crew',
    'Blonde Crewcut',
    'Blonde Medium',
    'Blonde Short',
    'Braids',
    'Brown Cowlick',
    'Brown Moptop',
    'Brown Pompadour',
    'Brown Short',
    'Brown Taper',
    'Brunette Bob',
    'Brunette Bun',
    'Brunette Long Ponytail',
    'Brunette Medium',
    'Brunette Ponytail',
    'Brunette Short',
    'Brunette Wavy Ponytail',
    'Cheetah',
    'Crazy Blue',
    'Crazy Orange',
    'Crazy Purple',
    'Custom',
    'Flat Top',
    'Light Brown Short',
    'Light Brunette Bob',
    'Patchy',
    'Pink Pigtails',
    'Pink Ponytail',
    'Purple Cowlick',
    'Red Crew',
    'Redhead Bun',
    'Redhead Ponytail',
    'Shaved',
    'Spiked',
    'Striped',
    'Thinning',
    'Very Thin'
  ],
  accessories: [
    '3D Glasses',
    'Arm Tattoo',
    'Armband',
    'Armband, 3D Glasses',
    'Armband, Arm Tattoo',
    'Armband, Clock Necklace',
    'Armband, Cyborg Eye',
    'Armband, Earrings',
    'Armband, Eye Patch',
    'Armband, Glasses',
    'Armband, Goggles',
    'Armband, Gold Chain',
    'Armband, Gold Headphones',
    'Armband, Grey Headphones',
    'Armband, Headband',
    'Armband, Headband, 3D Glasses',
    'Armband, Headband, Arm Tattoo',
    'Armband, Headband, Clock Necklace',
    'Armband, Headband, Cyborg Eye',
    'Armband, Headband, Earrings',
    'Armband, Headband, Eye Patch',
    'Armband, Headband, Glasses',
    'Armband, Headband, Goggles',
    'Armband, Headband, Gold Chain',
    'Armband, Headband, Gold Headphones',
    'Armband, Headband, Grey Headphones',
    'Armband, Headband, Nasal Strip',
    'Armband, Headband, Pencil',
    'Armband, Headband, Red Headphones',
    'Armband, Headband, Silver Chain',
    'Armband, Headband, Space Visor',
    'Armband, Headband, Steampunk Goggles',
    'Armband, Nasal Strip',
    'Armband, Pencil',
    'Armband, Red Headphones',
    'Armband, Silver Chain',
    'Armband, Space Visor',
    'Armband, Steampunk Goggles',
    'Clock Necklace',
    'Cyborg Eye',
    'Earrings',
    'Eye Patch',
    'Glasses',
    'Goggles',
    'Gold Chain',
    'Gold Headphones',
    'Grey Headphones',
    'Headband',
    'Headband, 3D Glasses',
    'Headband, Arm Tattoo',
    'Headband, Clock Necklace',
    'Headband, Cyborg Eye',
    'Headband, Earrings',
    'Headband, Eye Patch',
    'Headband, Glasses',
    'Headband, Goggles',
    'Headband, Gold Chain',
    'Headband, Gold Headphones',
    'Headband, Grey Headphones',
    'Headband, Nasal Strip',
    'Headband, Pencil',
    'Headband, Red Headphones',
    'Headband, Silver Chain',
    'Headband, Space Visor',
    'Headband, Steampunk Goggles',
    'Nasal Strip',
    'None',
    'Pencil',
    'Red Headphones',
    'Silver Chain',
    'Space Visor',
    'Steampunk Goggles'
  ],
  dunks: sixtyUntilNinetyNineArray,
  shooting: sixtyUntilNinetyNineArray,
  playmaking: sixtyUntilNinetyNineArray,
  defense: sixtyUntilNinetyNineArray
};
